# Generated by Django 5.2.8 on 2025-12-11 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerse_app', '0002_user_province'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prodcut_name',
            new_name='product_name',
        ),
    ]
